version: '3'
services:
  web:
    container_name: web
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - couchbase
  db:
    container_name: db
    image: postgres
    # volumes:
    #   - ./docker-volumes/postgres:/var/lib/postgresql/data
  couchbase:
    container_name: couchbase
    image: arungupta/couchbase
    deploy:
      replicas: 1
    # volumes:
    #   - ./docker-volumes/couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
